packages:
  - .
autoInstallPeers: true
catalogs:
  silk:
    turbo: ^2.8.3
    typescript: ^5.9.3
    "@types/node": ^25.2.0
    "@typescript/native-preview": ^7.0.0-dev.20260203.1
    vitest: ^4.0.18
    "@vitest/coverage-v8": ^4.0.18
    "@changesets/cli": ^2.29.8
    "@microsoft/api-extractor": ^7.56.0
    "@rslib/core": ^0.19.4
  silkPeers:
    "@microsoft/api-extractor": ^7.55.2
    "@rslib/core": ^0.19.3
    "@types/node": ^25.0.10
    "@typescript/native-preview": ^7.0.0-dev.20260124.1
    typescript: ^5.9.3
    "@commitlint/cli": ^20.4.1
    "@commitlint/config-conventional": ^20.4.1
    commitizen: ^4.3.1
    husky: ^9.1.7
    "@biomejs/biome": ^2.3.12
    lint-staged: ^16.2.7
    markdownlint-cli2: ^0.20.0
    markdownlint-cli2-formatter-codequality: ^0.0.7
loglevel: info
onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js
  - esbuild
  - msgpackr-extract
preferFrozenLockfile: true
publicHoistPattern:
  - "@commitlint/cli"
  - "@commitlint/config-conventional"
  - "@commitlint/cz-commitlint"
  - husky
  - lint-staged
  - markdownlint-cli2
  - markdownlint-cli2-formatter-codequality
