packages:
  - .
autoInstallPeers: true
catalogs:
  silk:
    "@types/node": ^25.3.3
    "@typescript/native-preview": ^7.0.0-dev.20260308.1
    husky: ^9.1.7
    tsx: ^4.21.0
    typescript: ^5.9.3
  silkPeers:
    "@types/node": ^25.2.0
    "@typescript/native-preview": ^7.0.0-dev.20260124.1
    husky: ^9.1.0
    tsx: ^4.21.0
    typescript: ^5.9.3
loglevel: info
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@savvy-web/changesets"
  - "@savvy-web/commitlint"
  - "@savvy-web/github-action-builder"
  - "@savvy-web/lint-staged"
  - "@savvy-web/vitest"
  - core-js
  - esbuild
  - msgpackr-extract
overrides:
  "@isaacs/brace-expansion": ^5.0.1
  lodash: ^4.17.23
  markdown-it: ^14.1.1
  tmp: ^0.2.4
  minimatch: ">=10.2.3"
publicHoistPattern:
  - "@changesets/cli"
  - "@commitlint/cli"
  - "@commitlint/config-conventional"
  - "@commitlint/cz-commitlint"
  - "@microsoft/api-extractor"
  - "@rslib/core"
  - "@types/node"
  - "@typescript/native-preview"
  - "@vitest/coverage-v8"
  - commitizen
  - husky
  - lint-staged
  - markdownlint-cli2
  - markdownlint-cli2-formatter-codequality
  - tsx
  - turbo
  - typescript
  - vitest
