packages:
  - .
autoInstallPeers: true
catalogs:
  silk:
    "@biomejs/biome": 2.4.1
    "@changesets/cli": ^2.29.8
    "@commitlint/cli": ^20.4.1
    "@commitlint/config-conventional": ^20.4.1
    "@microsoft/api-extractor": ^7.56.3
    "@rslib/core": ^0.19.6
    "@types/node": ^25.2.3
    "@typescript/native-preview": 7.0.0-dev.20260217.1
    "@vitest/coverage-v8": ^4.0.18
    commitizen: ^4.3.1
    husky: ^9.1.7
    lint-staged: ^16.2.7
    markdownlint-cli2: ^0.21.0
    markdownlint-cli2-formatter-codequality: ^0.0.7
    tsx: ^4.21.0
    turbo: ^2.8.9
    typescript: ^5.9.3
    vitest: ^4.0.18
  silkPeers:
    "@biomejs/biome": 2.4.1
    "@changesets/cli": ^2.29.0
    "@commitlint/cli": ^20.4.0
    "@commitlint/config-conventional": ^20.4.0
    "@microsoft/api-extractor": ^7.56.0
    "@rslib/core": ^0.19.6
    "@types/node": ^25.2.0
    "@typescript/native-preview": ^7.0.0-dev.20260124.1
    "@vitest/coverage-v8": ^4.0.18
    commitizen: ^4.3.0
    husky: ^9.1.0
    lint-staged: ^16.2.0
    markdownlint-cli2: ^0.21.0
    markdownlint-cli2-formatter-codequality: ^0.0.7
    tsx: ^4.21.0
    turbo: ^2.8.0
    typescript: ^5.9.3
    vitest: ^4.0.18
loglevel: info
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@savvy-web/changesets"
  - "@savvy-web/commitlint"
  - "@savvy-web/github-action-builder"
  - "@savvy-web/lint-staged"
  - "@savvy-web/vitest"
  - core-js
  - esbuild
  - msgpackr-extract
overrides:
  "@isaacs/brace-expansion": ^5.0.1
  lodash: ^4.17.23
  markdown-it: ^14.1.1
  tmp: ^0.2.4
publicHoistPattern:
  - "@changesets/cli"
  - "@commitlint/cli"
  - "@commitlint/config-conventional"
  - "@commitlint/cz-commitlint"
  - "@microsoft/api-extractor"
  - "@rslib/core"
  - "@types/node"
  - "@typescript/native-preview"
  - "@vitest/coverage-v8"
  - commitizen
  - husky
  - lint-staged
  - markdownlint-cli2
  - markdownlint-cli2-formatter-codequality
  - tsx
  - turbo
  - typescript
  - vitest
