/**
 * Auto-generated Silk catalog definitions.
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, update pnpm-workspace.yaml and run: pnpm run generate:catalogs
 *
 * Generated: 2026-02-04T14:56:35.492Z
 *
 * @packageDocumentation
 */

import type { SilkCatalogs } from "./types.js";

/**
 * The complete Silk catalogs generated from pnpm-workspace.yaml.
 *
 * - `silk`: Current/latest versions for direct dependencies
 * - `silkPeers`: Permissive ranges for peerDependencies
 */
export const silkCatalogs: SilkCatalogs = {
	silk: {
		"@changesets/cli": "^2.29.8",
		"@microsoft/api-extractor": "^7.56.0",
		"@rslib/core": "^0.19.4",
		"@types/node": "^25.2.0",
		"@typescript/native-preview": "^7.0.0-dev.20260203.1",
		"@vitest/coverage-v8": "^4.0.18",
		turbo: "^2.8.3",
		typescript: "^5.9.3",
		vitest: "^4.0.18",
	},
	silkPeers: {
		"@biomejs/biome": "^2.3.12",
		"@commitlint/cli": "^20.4.1",
		"@commitlint/config-conventional": "^20.4.1",
		"@microsoft/api-extractor": "^7.55.2",
		"@rslib/core": "^0.19.3",
		"@types/node": "^25.0.10",
		"@typescript/native-preview": "^7.0.0-dev.20260124.1",
		commitizen: "^4.3.1",
		husky: "^9.1.7",
		"lint-staged": "^16.2.7",
		"markdownlint-cli2": "^0.20.0",
		"markdownlint-cli2-formatter-codequality": "^0.0.7",
		typescript: "^5.9.3",
	},
};
