/**
 * Auto-generated Silk catalog definitions.
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, update pnpm-workspace.yaml and run: pnpm run generate:catalogs
 *
 * Generated: 2026-03-17T17:39:42.363Z
 *
 * @packageDocumentation
 */

import type { SilkCatalogs } from "./types.js";

/**
 * The complete Silk catalogs generated from pnpm-workspace.yaml.
 *
 * - `silk`: Current/latest versions for direct dependencies
 * - `silkPeers`: Permissive ranges for peerDependencies
 * - `silkOverrides`: Security overrides for known CVEs
 * - `silkOnlyBuiltDependencies`: Packages allowed to run build scripts
 * - `silkPublicHoistPattern`: Packages to hoist to virtual store root
 */
export const silkCatalogs: SilkCatalogs = {
	silk: {
		"@effect/cli": "^0.74.0",
		"@effect/cluster": "^0.57.0",
		"@effect/language-service": "^0.80.0",
		"@effect/opentelemetry": "^0.62.0",
		"@effect/platform": "^0.95.0",
		"@effect/platform-bun": "^0.88.0",
		"@effect/platform-node": "^0.105.0",
		"@effect/printer": "^0.48.0",
		"@effect/printer-ansi": "^0.48.0",
		"@effect/rpc": "^0.74.0",
		"@effect/sql": "^0.50.0",
		"@effect/typeclass": "^0.39.0",
		"@types/node": "^25.5.0",
		"@typescript/native-preview": "7.0.0-dev.20260317.1",
		effect: "^3.20.0",
		husky: "^9.1.7",
		tsx: "^4.21.0",
		typescript: "^5.9.3",
	},
	silkPeers: {
		"@effect/cli": ">=0.73.0",
		"@effect/cluster": ">=0.56.0",
		"@effect/language-service": ">=0.79.0",
		"@effect/opentelemetry": ">=0.61.0",
		"@effect/platform": ">=0.94.0",
		"@effect/platform-bun": ">=0.87.0",
		"@effect/platform-node": ">=0.104.0",
		"@effect/printer": ">=0.47.0",
		"@effect/printer-ansi": ">=0.47.0",
		"@effect/rpc": ">=0.73.0",
		"@effect/sql": ">=0.49.0",
		"@effect/typeclass": ">=0.38.0",
		"@types/node": "^25.2.0",
		"@typescript/native-preview": "^7.0.0-dev.20260124.1",
		effect: "^3.19.0",
		husky: "^9.1.0",
		tsx: "^4.21.0",
		typescript: "^5.9.3",
	},
	silkOverrides: {
		"@isaacs/brace-expansion": "^5.0.1",
		lodash: "^4.17.23",
		"markdown-it": "^14.1.1",
		minimatch: ">=10.2.3",
		tmp: "^0.2.4",
	},
	silkOnlyBuiltDependencies: [
		"@parcel/watcher",
		"@savvy-web/changesets",
		"@savvy-web/commitlint",
		"@savvy-web/github-action-builder",
		"@savvy-web/lint-staged",
		"@savvy-web/vitest",
		"core-js",
		"esbuild",
		"msgpackr-extract",
	],
	silkPublicHoistPattern: [
		"@changesets/cli",
		"@commitlint/cli",
		"@commitlint/config-conventional",
		"@commitlint/cz-commitlint",
		"@microsoft/api-extractor",
		"@rslib/core",
		"@types/node",
		"@typescript/native-preview",
		"@vitest/coverage-v8",
		"commitizen",
		"husky",
		"lint-staged",
		"markdownlint-cli2",
		"markdownlint-cli2-formatter-codequality",
		"tsx",
		"turbo",
		"typescript",
		"vitest",
	],
};
