/**
 * Auto-generated Silk catalog definitions.
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, update pnpm-workspace.yaml and run: pnpm run generate:catalogs
 *
 * Generated: 2026-03-28T06:30:09.177Z
 *
 * @packageDocumentation
 */

import type { SilkCatalogs } from "./types.js";

/**
 * The complete Silk catalogs generated from pnpm-workspace.yaml.
 *
 * - `silk`: Current/latest versions for direct dependencies
 * - `silkPeers`: Permissive ranges for peerDependencies
 * - `silkOverrides`: Security overrides for known CVEs
 * - `silkOnlyBuiltDependencies`: Packages allowed to run build scripts
 * - `silkPublicHoistPattern`: Packages to hoist to virtual store root
 */
export const silkCatalogs: SilkCatalogs = {
	silk: {
		"@biomejs/biome": "2.4.9",
		"@effect/ai": "^0.35.0",
		"@effect/ai-anthropic": "^0.25.0",
		"@effect/ai-openai": "^0.39.0",
		"@effect/cli": "^0.75.0",
		"@effect/cluster": "^0.58.0",
		"@effect/experimental": "^0.60.0",
		"@effect/language-service": "^0.84.0",
		"@effect/opentelemetry": "^0.63.0",
		"@effect/platform": "^0.96.0",
		"@effect/platform-bun": "^0.89.0",
		"@effect/platform-node": "^0.106.0",
		"@effect/printer": "^0.49.0",
		"@effect/printer-ansi": "^0.49.0",
		"@effect/rpc": "^0.75.0",
		"@effect/sql": "^0.51.0",
		"@effect/sql-sqlite-node": "^0.52.0",
		"@effect/typeclass": "^0.40.0",
		"@effect/workflow": "^0.18.0",
		"@types/node": "^25.5.0",
		"@typescript/native-preview": "^7.0.0-dev.20260327.2",
		effect: "^3.21.0",
		husky: "^9.1.7",
		tsx: "^4.21.0",
		typescript: "^5.9.3",
	},
	silkPeers: {
		"@biomejs/biome": "2.4.9",
		"@effect/ai": ">=0.35.0",
		"@effect/ai-anthropic": ">=0.25.0",
		"@effect/ai-openai": ">=0.39.0",
		"@effect/cli": ">=0.75.0",
		"@effect/cluster": ">=0.58.0",
		"@effect/experimental": ">=0.60.0",
		"@effect/language-service": ">=0.84.0",
		"@effect/opentelemetry": ">=0.63.0",
		"@effect/platform": ">=0.96.0",
		"@effect/platform-bun": ">=0.89.0",
		"@effect/platform-node": ">=0.106.0",
		"@effect/printer": ">=0.49.0",
		"@effect/printer-ansi": ">=0.49.0",
		"@effect/rpc": ">=0.75.0",
		"@effect/sql": ">=0.51.0",
		"@effect/sql-sqlite-node": ">=0.52.0",
		"@effect/typeclass": ">=0.40.0",
		"@effect/workflow": ">=0.18.0",
		"@types/node": "^25.5.0",
		"@typescript/native-preview": "^7.0.0-dev.20260124.1",
		effect: ">=3.21.0",
		husky: "^9.1.0",
		tsx: "^4.21.0",
		typescript: "^5.9.3",
	},
	silkOverrides: {
		"@isaacs/brace-expansion": "^5.0.1",
		lodash: "^4.17.23",
		"markdown-it": "^14.1.1",
		minimatch: ">=10.2.3",
		"smol-toml": ">=1.6.1",
		tmp: "^0.2.4",
	},
	silkOnlyBuiltDependencies: [
		"@parcel/watcher",
		"@savvy-web/changesets",
		"@savvy-web/commitlint",
		"@savvy-web/github-action-builder",
		"@savvy-web/lint-staged",
		"@savvy-web/vitest",
		"better-sqlite3",
		"core-js",
		"esbuild",
		"msgpackr-extract",
	],
	silkPublicHoistPattern: [
		"@changesets/cli",
		"@commitlint/cli",
		"@commitlint/config-conventional",
		"@commitlint/cz-commitlint",
		"@microsoft/api-extractor",
		"@rslib/core",
		"@types/node",
		"@typescript/native-preview",
		"@vitest/coverage-v8",
		"commitizen",
		"husky",
		"lint-staged",
		"markdownlint-cli2",
		"markdownlint-cli2-formatter-codequality",
		"tsx",
		"turbo",
		"typescript",
		"vitest",
		"vitest-agent-reporter",
	],
};
