/**
 * Effect program that generates TypeScript catalog files from pnpm-workspace.yaml.
 *
 * Uses the FileSystem service for all I/O, making it testable with mock filesystems.
 *
 * @packageDocumentation
 */

import { FileSystem } from "@effect/platform/FileSystem";
import { Data, Effect } from "effect";
import { parse as parseYaml } from "yaml";

/**
 * Typed error for catalog generation failures.
 */
export class GenerateError extends Data.TaggedError("GenerateError")<{
	readonly message: string;
}> {}

interface WorkspaceConfig {
	catalogs?: {
		silk?: Record<string, string>;
		silkPeers?: Record<string, string>;
	};
	overrides?: Record<string, string>;
	onlyBuiltDependencies?: string[];
	publicHoistPattern?: string[];
	peerDependencyRules?: {
		allowedVersions?: Record<string, string>;
		ignoreMissing?: string[];
		allowAny?: string[];
	};
}

/**
 * Format a catalog object as TypeScript code.
 */
function formatCatalog(catalog: Record<string, string>, indent = "\t\t"): string {
	const entries = Object.entries(catalog)
		.sort(([a], [b]) => a.localeCompare(b))
		.map(([pkg, version]) => {
			// Quote package names that contain special characters
			const key = pkg.includes("/") || pkg.includes("-") ? `"${pkg}"` : pkg;
			return `${indent}${key}: "${version}",`;
		});
	return entries.join("\n");
}

/**
 * Format a string array as TypeScript code.
 */
function formatStringArray(items: string[], indent = "\t\t"): string {
	const sortedItems = [...items].sort((a, b) => a.localeCompare(b));
	return sortedItems.map((item) => `${indent}"${item}",`).join("\n");
}

/**
 * Format a string array as a complete TypeScript array literal.
 * Returns `[]` for empty arrays and multi-line `[\n...\n\t]` for non-empty ones.
 */
function formatArrayLiteral(items: string[], indent = "\t\t"): string {
	if (items.length === 0) return "[]";
	const inner = formatStringArray(items, indent);
	return `[\n${inner}\n\t]`;
}

/**
 * Format a catalog object as a complete TypeScript object literal.
 * Returns `{}` for empty objects and multi-line `{\n...\n\t}` for non-empty ones.
 */
function formatCatalogLiteral(catalog: Record<string, string>, indent = "\t\t"): string {
	if (Object.keys(catalog).length === 0) return "{}";
	const inner = formatCatalog(catalog, indent);
	return `{\n${inner}\n\t}`;
}

/**
 * Generate the TypeScript catalog file content.
 */
function generateContent(
	silk: Record<string, string>,
	silkPeers: Record<string, string>,
	silkOverrides: Record<string, string>,
	silkOnlyBuiltDependencies: string[],
	silkPublicHoistPattern: string[],
	silkPeerDependencyRules: { allowedVersions: Record<string, string>; ignoreMissing: string[]; allowAny: string[] },
	timestamp: string,
): string {
	return `/**
 * Auto-generated Silk catalog definitions.
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, update pnpm-workspace.yaml and run: pnpm run generate:catalogs
 *
 * Generated: ${timestamp}
 *
 * @packageDocumentation
 */

import type { SilkCatalogs, SilkPeerDependencyRules } from "./types.js";

/**
 * The complete Silk catalogs generated from pnpm-workspace.yaml.
 *
 * - \`silk\`: Current/latest versions for direct dependencies
 * - \`silkPeers\`: Permissive ranges for peerDependencies
 * - \`silkOverrides\`: Security overrides for known CVEs
 * - \`silkOnlyBuiltDependencies\`: Packages allowed to run build scripts
 * - \`silkPublicHoistPattern\`: Packages to hoist to virtual store root
 */
export const silkCatalogs: SilkCatalogs = {
\tsilk: {
${formatCatalog(silk)}
\t},
\tsilkPeers: {
${formatCatalog(silkPeers)}
\t},
\tsilkOverrides: {
${formatCatalog(silkOverrides)}
\t},
\tsilkOnlyBuiltDependencies: [
${formatStringArray(silkOnlyBuiltDependencies)}
\t],
\tsilkPublicHoistPattern: [
${formatStringArray(silkPublicHoistPattern)}
\t],
};

/**
 * Peer dependency rules generated from pnpm-workspace.yaml.
 */
export const silkPeerDependencyRules: SilkPeerDependencyRules = {
\tallowedVersions: ${formatCatalogLiteral(silkPeerDependencyRules.allowedVersions)},
\tignoreMissing: ${formatArrayLiteral(silkPeerDependencyRules.ignoreMissing)},
\tallowAny: ${formatArrayLiteral(silkPeerDependencyRules.allowAny)},
};
`;
}

/**
 * Generate TypeScript catalog file from a workspace YAML configuration.
 *
 * @param workspacePath - Absolute path to pnpm-workspace.yaml
 * @param outputPath - Absolute path to the output TypeScript file
 * @param timestamp - Optional fixed timestamp for deterministic output (ISO string)
 * @returns Effect that yields `{ warnings: string[] }` on success
 */
export function generateCatalogs(
	workspacePath: string,
	outputPath: string,
	timestamp?: string,
): Effect.Effect<{ warnings: string[] }, GenerateError, FileSystem> {
	return Effect.gen(function* () {
		const fs = yield* FileSystem;

		// Read and parse workspace config
		const yamlContent = yield* fs.readFileString(workspacePath).pipe(
			Effect.mapError(
				(err) =>
					new GenerateError({
						message: `Failed to read workspace config: ${err.message}`,
					}),
			),
		);

		const config = parseYaml(yamlContent) as WorkspaceConfig;

		// Validate required catalogs
		if (!config.catalogs?.silk) {
			return yield* new GenerateError({
				message: "No 'catalogs.silk' found in pnpm-workspace.yaml",
			});
		}

		if (!config.catalogs?.silkPeers) {
			return yield* new GenerateError({
				message: "No 'catalogs.silkPeers' found in pnpm-workspace.yaml",
			});
		}

		const silk = config.catalogs.silk;
		const silkPeers = config.catalogs.silkPeers;
		const silkOverrides = config.overrides ?? {};
		const silkOnlyBuiltDependencies = config.onlyBuiltDependencies ?? [];
		const silkPublicHoistPattern = config.publicHoistPattern ?? [];
		const silkPeerDependencyRules = {
			allowedVersions: config.peerDependencyRules?.allowedVersions ?? {},
			ignoreMissing: config.peerDependencyRules?.ignoreMissing ?? [],
			allowAny: config.peerDependencyRules?.allowAny ?? [],
		};

		const ts = timestamp ?? new Date().toISOString();
		const content = generateContent(
			silk,
			silkPeers,
			silkOverrides,
			silkOnlyBuiltDependencies,
			silkPublicHoistPattern,
			silkPeerDependencyRules,
			ts,
		);

		// Only write if content changed (ignoring the timestamp line)
		const timestampPattern = / \* Generated: .+/;
		const stripTimestamp = (s: string) => s.replace(timestampPattern, "");

		const fileExists = yield* fs.exists(outputPath).pipe(
			Effect.mapError(
				(err) =>
					new GenerateError({
						message: `Failed to check output file: ${err.message}`,
					}),
			),
		);

		const warnings = Object.keys(silk)
			.filter((pkg) => !(pkg in silkPeers))
			.map((pkg) => `Package in silk but not silkPeers: ${pkg}`);

		if (fileExists) {
			const existing = yield* fs.readFileString(outputPath).pipe(
				Effect.mapError(
					(err) =>
						new GenerateError({
							message: `Failed to read existing output: ${err.message}`,
						}),
				),
			);

			if (stripTimestamp(existing) === stripTimestamp(content)) {
				return { warnings };
			}
		}

		// Write the generated content
		yield* fs.writeFileString(outputPath, content).pipe(
			Effect.mapError(
				(err) =>
					new GenerateError({
						message: `Failed to write output: ${err.message}`,
					}),
			),
		);

		return { warnings };
	});
}
